### ISSUE TITLE
Towers of Hanoi Issue (Computational Explosion)

### ISSUE THREAD

**Issue by MFaisalZaki** [ztangent/Plinf.jl#2]
Hello, I'm trying to solve the towers of hanoi using PDDL is works fine with 3 and 4 disks count. However, when I increase the disks count it fails and generates a nothing plan.

I'm attaching both the problem domain and instance.

Can you help me fix this issue?
[Archive.zip](https://github.com/ztangent/Plinf.jl/files/4938785/Archive.zip)

**Comment by ztangent** [comment]
Did you manage to solve this? It's possibly an issue with the planner timing out when it reaches the maximum number of nodes. I've recently added support for a backward chaining planner (`BackwardPlanner'), which _may_ be able to solve some problems that forward chaining can't.

**Comment by MFaisalZaki** [comment]
Yes, I had to add more facts to show that disk A is the smallest followed by disk B and so on.
